/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogChooser.java
 *
 * Created on 09.07.2011, 14:26:29
 */
package filechoser;

import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JViewport;
import sun.swing.FilePane;

/**
 *
 * @author dimon
 */
public class JDialogChooser extends javax.swing.JDialog {

    public final Font DEFAULT_FONT = new Font("Vedanta", 0, 14);
    private JFileChooser fileChooser = null;
    private JComboBox comboBoxPlaces = null;
    private JButton buttonGoUp = null;
    private JButton buttonDesktop = null;
    private JButton buttonNewFolder = null;
    private JTextField fileName = null;
    private JComboBox comboBoxType = null;

    /** Creates new form JDialogChooser */
    public JDialogChooser(java.awt.Frame parent, boolean modal, JFileChooser fileChooser) {
        super(parent, modal);
        this.fileChooser = fileChooser;
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setComponentPopupMenu(new JPopupMenu());

       // FilePane filePane = (FilePane) fileChooser.getComponent(2);

        comboBoxPlaces = (JComboBox) ((JPanel) fileChooser.getComponent(0)).getComponent(2);
        buttonGoUp = (JButton) ((JPanel) ((JPanel) fileChooser.getComponent(0)).getComponent(0)).getComponent(0);
        buttonDesktop = (JButton) ((JPanel) ((JPanel) fileChooser.getComponent(0)).getComponent(0)).getComponent(2);
        buttonNewFolder = (JButton) ((JPanel) ((JPanel) fileChooser.getComponent(0)).getComponent(0)).getComponent(4);
        fileName = (JTextField) ((JPanel) ((JPanel) ((JPanel) fileChooser.getComponent(3))).getComponent(0)).getComponent(1);
        comboBoxType = (JComboBox) ((JPanel) ((JPanel) ((JPanel) fileChooser.getComponent(3))).getComponent(2)).getComponent(1);
        initComponents();
        jComboBoxPlaces = comboBoxPlaces;
        jButtonGoUp = buttonGoUp;
        jButtonDesktop = buttonDesktop;
        jButtonNewFolder = buttonNewFolder;
        jTextFieldFileName = fileName;
        jComboBoxType = comboBoxType;
        GroupLayout jPanelFilePaneLayout = new GroupLayout(jPanelFilePane);
        jPanelFilePane.setLayout(jPanelFilePaneLayout);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFileSystemData = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPlaces = new javax.swing.JComboBox();
        jButtonGoUp = new javax.swing.JButton();
        jButtonDesktop = new javax.swing.JButton();
        jButtonNewFolder = new javax.swing.JButton();
        jPanelFilePane = new javax.swing.JPanel();
        jPanelFileNameType = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFileName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jaudioeditor.JAudioEditorApp.class).getContext().getResourceMap(JDialogChooser.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 400));
        setName("Form"); // NOI18N

        jPanelFileSystemData.setName("jPanelFileSystemData"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setFont(DEFAULT_FONT);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jComboBoxPlaces.setName("jComboBoxPlaces"); // NOI18N

        jButtonGoUp.setText(resourceMap.getString("jButtonGoUp.text")); // NOI18N
        jButtonGoUp.setName("jButtonGoUp"); // NOI18N

        jButtonDesktop.setText(resourceMap.getString("jButtonDesktop.text")); // NOI18N
        jButtonDesktop.setName("jButtonDesktop"); // NOI18N

        jButtonNewFolder.setText(resourceMap.getString("jButtonNewFolder.text")); // NOI18N
        jButtonNewFolder.setName("jButtonNewFolder"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGoUp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonNewFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButtonDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButtonGoUp, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxPlaces)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanelFilePane.setBackground(resourceMap.getColor("jPanelFilePane.background")); // NOI18N
        jPanelFilePane.setName("jPanelFilePane"); // NOI18N

        javax.swing.GroupLayout jPanelFilePaneLayout = new javax.swing.GroupLayout(jPanelFilePane);
        jPanelFilePane.setLayout(jPanelFilePaneLayout);
        jPanelFilePaneLayout.setHorizontalGroup(
            jPanelFilePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanelFilePaneLayout.setVerticalGroup(
            jPanelFilePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        jPanelFileNameType.setName("jPanelFileNameType"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldFileName.setText(resourceMap.getString("jTextFieldFileName.text")); // NOI18N
        jTextFieldFileName.setName("jTextFieldFileName"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxType.setName("jComboBoxType"); // NOI18N

        javax.swing.GroupLayout jPanelFileNameTypeLayout = new javax.swing.GroupLayout(jPanelFileNameType);
        jPanelFileNameType.setLayout(jPanelFileNameTypeLayout);
        jPanelFileNameTypeLayout.setHorizontalGroup(
            jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileNameTypeLayout.createSequentialGroup()
                .addGroup(jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFileNameTypeLayout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelFileNameTypeLayout.setVerticalGroup(
            jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileNameTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFileNameTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout jPanelFileSystemDataLayout = new javax.swing.GroupLayout(jPanelFileSystemData);
        jPanelFileSystemData.setLayout(jPanelFileSystemDataLayout);
        jPanelFileSystemDataLayout.setHorizontalGroup(
            jPanelFileSystemDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileSystemDataLayout.createSequentialGroup()
                .addGroup(jPanelFileSystemDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelFileNameType, javax.swing.GroupLayout.Alignment.LEADING, 0, 579, Short.MAX_VALUE)
                    .addComponent(jPanelFilePane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFileSystemDataLayout.setVerticalGroup(
            jPanelFileSystemDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFileSystemDataLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFilePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFileNameType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFileSystemData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFileSystemData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fileChooser.setSelectedFiles(null);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDesktop;
    private javax.swing.JButton jButtonGoUp;
    private javax.swing.JButton jButtonNewFolder;
    private javax.swing.JComboBox jComboBoxPlaces;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFileNameType;
    private javax.swing.JPanel jPanelFilePane;
    private javax.swing.JPanel jPanelFileSystemData;
    private javax.swing.JTextField jTextFieldFileName;
    // End of variables declaration//GEN-END:variables
}
