package jaudioeditor;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author dimon
 */
public class JFrameArtworkView extends javax.swing.JFrame {

    javax.swing.JPanel jPanelArt1 = new javax.swing.JPanel();
    javax.swing.JPanel jPanelArt2 = new javax.swing.JPanel();
    javax.swing.JScrollPane jScrollPaneArt1 = new javax.swing.JScrollPane();
    javax.swing.JPanel jPanelArt3 = new javax.swing.JPanel();
    javax.swing.JLabel jLabelArt1 = new javax.swing.JLabel();

    /**
     * Creates new form JFrameArtworkView
     */
    public JFrameArtworkView(Image img) {
        init(img);
    }

    private void init(Image img) {
        this.getContentPane().setLayout(new java.awt.GridLayout());
        this.setName("Artwork");
        jPanelArt2.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanelArt2.setLayout(new java.awt.GridLayout());

        jPanelArt3.setLayout(new java.awt.GridLayout());

        jLabelArt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelArt3.add(jLabelArt1);

        jScrollPaneArt1.setViewportView(jPanelArt3);

        jPanelArt2.add(jScrollPaneArt1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanelArt1);
        jPanelArt1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jPanelArt2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE).addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jPanelArt2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE).addContainerGap()));

        this.getContentPane().add(jPanelArt1);

        this.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getPreferredSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        jLabelArt1.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
